Keep updating v5 for catalogs

diff --git a/.github/workflows/update-aws-catalog.yml b/.github/workflows/update-aws-catalog.yml
--- a/.github/workflows/update-aws-catalog.yml
+++ b/.github/workflows/update-aws-catalog.yml
@@ -24,36 +24,45 @@ jobs:
           fetch-depth: 0
           path: catalogs
           token: ${{ secrets.GH_ACTION_PAT }}
-      - name: Set up Python 3.10
-        uses: actions/setup-python@v5
+      - name: Install the latest version of uv
+        uses: astral-sh/setup-uv@v4
         with:
-          python-version: '3.10'
-          cache: 'pip' # caching pip dependencies
-      - name: Install dependencies
-        run: |
-          python -m pip install --upgrade pip
-          cd sky
-          pip install ".[aws]"
-
+          version: "latest"
+          python-version: "3.10"
       - name: Run fetch_aws
+        id: fetch_catalogs
         run: |
-          version=$(python -c 'import sky; print(sky.clouds.service_catalog.constants.CATALOG_SCHEMA_VERSION)')
-          mkdir -p catalogs/catalogs/$version
-          cd catalogs/catalogs/$version
-          # Uses --check-all-regions-enabled-for-account to ensure that the catalog fetched has all regions, otherwise fail the job.
-          python -m sky.clouds.service_catalog.data_fetchers.fetch_aws --no-az-mappings --check-all-regions-enabled-for-account
+          versions=$(cat .metadata.yml | yq -r '.version_commit | keys[]')
+          # Loop over all versions and commit hashes
+          for version in $versions; do
+            # Find commit hash for the version
+            commit_hash=$(cat .metadata.yml | yq -r '.version_commit | .[] | select(. == $version)')
+            cd sky
+            git checkout $commit_hash
+            uv pip install ".[aws]"
+            cd -
+            echo "Fetching AWS catalog for version $version, SkyPilot commit hash $commit_hash"
+            mkdir -p catalogs/catalogs/$version
+            cd catalogs/catalogs/$version
+            # Uses --check-all-regions-enabled-for-account to ensure that the catalog fetched has all regions, otherwise fail the job.
+            python -m sky.clouds.service_catalog.data_fetchers.fetch_aws --no-az-mappings --check-all-regions-enabled-for-account
+          done
+          echo "versions=$versions" >> $GITHUB_OUTPUT
+          echo "commit_hashes=$commit_hashes" >> $GITHUB_OUTPUT
         env:
           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
 
       - name: Commit catalog
         run: |
-          version=$(python -c 'import sky; print(sky.clouds.service_catalog.constants.CATALOG_SCHEMA_VERSION)')
           cd catalogs
           git config --global user.name 'github-actions[bot]'
           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
           git add .
-          git commit -m"[Bot] Update AWS catalog $version (scheduled at $(date))" || { echo "No changes to commit" && exit 0; }
+          git commit -m"[Bot] Update AWS catalog $VERSIONS (scheduled at $(date))" || { echo "No changes to commit" && exit 0; }
           git fetch origin
           git rebase origin/master
           git push
+        env:
+          VERSIONS: ${{ steps.fetch_catalogs.outputs.versions }}
+      
